services:

  frontend:
    build: .

    ports:
      - "5173:5173"

    environment:
      - VITE_GATEWAY_API_URL=http://localhost:8000/api

    networks:
      - frontend-network


networks:

  frontend-network: