services:

  gateway-lb:
    image: nginx:latest

    ports:
      - "8000:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - api-gateway-1
      - api-gateway-2
      - api-gateway-3

    networks:
      - gateway-network


  api-gateway-1:
    build: ./service

    env_file:
      - .env

    networks:
      - gateway-network
      - service-network

  api-gateway-2:
    build: ./service

    env_file:
      - .env

    networks:
      - gateway-network
      - service-network
      
  api-gateway-3:
    build: ./service

    env_file:
      - .env

    networks:
      - gateway-network
      - service-network


networks:

  gateway-network:

  service-network:
    external: true